### ISSUE TITLE
🤔 Suggestion: Add right-click context menu to manage keys

### ISSUE THREAD

**Issue by pcgeek86** [redis-stack/redis-stack#225]
### Summary

When I right-click on an item, I would like to see a context menu with some options, like:

- Set a new TTL
- Delete the key

### Current Behavior

When I right-click on an item, I get the standard browser context menu.

![image](https://user-images.githubusercontent.com/466713/194721903-3a9ca4a0-dc87-4798-b92e-7dad023f7f85.png)

**Comment by chayim** [comment]
@ViktarStarastsenka Can you move this to RedisInsight please? This belongs there.

**Comment by ViktarStarastsenka** [comment]
@pcgeek86 , thank you for the idea. Let's discuss it under this ticket: https://github.com/RedisInsight/RedisInsight/issues/1355
