### ISSUE TITLE
install redis-stack on windows?

### ISSUE THREAD

**Issue by cuiboand1** [redis-stack/redis-stack#230]
install redis-stack on windows?

**Comment by nermiller** [comment]
Hi, @cuiboand1! I'm about to document instructions but you can use [Docker](https://redis.io/docs/stack/get-started/install/docker/) from PS. Let me know if you have any issues trying!

**Comment by chayim** [comment]
@nermiller I think we can close this, WDYT?

**Comment by nermiller** [comment]
Yes, I think we're good.
