### ISSUE TITLE
Support for older glibc versions with AppImage of Redis Stack

### ISSUE THREAD

**Issue by SolidTux** [redis-stack/redis-stack#275]
**The problem/use-case that the feature addresses**

Currently the AppImage for Redis Stack requires GLIBC 2.34. This prevents it from working with Debian (stable).

**Description of the feature**

Lower the required glibc version of the AppImage.

**Alternatives you've considered**

Building redis from source works, I have not tried manually loading all the modules contained in Stack.

**Additional information**

Running the AppImage under Debian bullseye results in

```
cut: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_redis-Tu9dh6/libunionpreload.so)
head: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_redis-Tu9dh6/libunionpreload.so)
grep: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_redis-Tu9dh6/libunionpreload.so)
sed: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_redis-Tu9dh6/libunionpreload.so)
```

**Comment by chayim** [comment]
@ofekshenawa We can probably build this on an older base image given the AppImage piece. Take a look at CORE18 instead of 20.
