### ISSUE TITLE
[Q] dockerhub release schedule

### ISSUE THREAD

**Issue by ddelange** [redis-stack/redis-stack#319]
Hi 👋

We noticed that `latest` points to [6.2.6-v2](https://hub.docker.com/layers/redis/redis-stack/6.2.6-v2/images/sha256-bdfb48d0b7822589fda98c19b52b74d0bf7b2f2d74ca50879599d26f734a7933?context=explore), yet redis's latest stable release is 7.0.8

Is there a specific reason why redis-stack v7 is not stable yet/why the docker tags between redis and redis-stack are out of sync?

**Comment by chayim** [comment]
@ViktarStarastsenka can you please answer @ddelange

**Comment by ViktarStarastsenka** [comment]
hi @ddelange , the latest version of Redis Stack is aligned with the default version in Redis Cloud.

**Comment by ddelange** [comment]
alright thanks! is there some docs you could link me to regarding the release schedule of redis cloud? when do you expect the first stable v7 release?

**Comment by ViktarStarastsenka** [comment]
@ddelange , nope, sorry, but currently, I cannot guide you to any document about the first stable Redis Stack v7, nor provide an approximate date.

**Comment by ddelange** [comment]
ok, then I guess it's living on the release-candidate-edge for now :)
