### ISSUE TITLE
RedisInsight - Automatic accept terms 

### ISSUE THREAD

**Issue by goodstas** [redis-stack/redis-stack#364]
Hello, i know that redis-stack docker image includes also RedisInsight. 
After running docker, i try to surf to localhost:8001 and it suppose to give me a window to accept the terms of using RedisInsight.
for some reason i don't get this window?
Is there is some parameter that i can provide through docker-compose file to automatically accept the terms and to see RedisInsight GUI?

Thank you.

**Comment by ViktarStarastsenka** [comment]
hi @goodstas, what window do you get?

**Comment by goodstas** [comment]
![RedisInsightEula](https://user-images.githubusercontent.com/35403839/225650543-7ee5bc93-0bc7-4eb2-a198-ca05ec4a51ea.jpg)
I attached the screenshot of the window to my response . It's EULA window.
I try to run the docker image redis-stack on the computer which does not have connection to the internet. 
May be this is the issue? May be RedisInsight try to connect to some server in the internet and it couldn't.
I thought that if there is some parameter to overcome this EULA window for getting straight to the RedisInsight GUI.

**Comment by ViktarStarastsenka** [comment]
@goodstas , yes, this is the issue. We will fix it with 2.22 (the next release is in late March, or early April).

**Comment by goodstas** [comment]
@ViktarStarastsenka thank you.

**Comment by chayim** [comment]
@ViktarStarastsenka Closing this, given that 2.22 was released with the last release. If it needs to be reopened, please update accordingly.
