### ISSUE TITLE
redis-stack:edge-arm64 not work on ARM64 Debian11.0

### ISSUE THREAD

**Issue by hxing** [redis-stack/redis-stack#389]
OS: Debian/bullseye on ARM64
Dokcer: 23.0.6
Docker Compose: v2.17.3

Execute following command to start container with default configuration. It got error and the container stopped. It seems GLIBCXX_3.4.29 is missing.

Current workaround is coping the redisearch.so from redis/redis-stack-server:latest image, and maping to the redis/redis-stack-server:edge-arm64.

The command can reproduce the issue:
docker run redis/redis-stack-server:edge-arm64

The full output:
10 May 2023 05:46:09.710 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
10 May 2023 05:46:09.711 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=8, just started
10 May 2023 05:46:09.711 # Configuration loaded
10 May 2023 05:46:09.711 * monotonic clock: POSIX clock_gettime
10 May 2023 05:46:09.712 * Running mode=standalone, port=6379.
10 May 2023 05:46:09.712 # Server initialized
10 May 2023 05:46:09.712 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
10 May 2023 05:46:09.714 # Module /opt/redis-stack/lib/redisearch.so failed to load: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/redis-stack/lib/redisearch.so)
10 May 2023 05:46:09.714 # Can't load module from /opt/redis-stack/lib/redisearch.so: server aborting

**Comment by chayim** [comment]
@hxing this is a known issue, and about to be fixed. We're waiting on the next redisearch:edge drop. Sorry for the inconvenience. As a result [this PR](https://github.com/redis-stack/redis-stack/pull/390) is in progress - though I appear to be stuck due to [this bug I reported](https://github.com/uraimo/run-on-arch-action/issues/126)
