### ISSUE TITLE
Deploy Redis Stack to k8s

### ISSUE THREAD

**Issue by edbergavera** [redis-stack/redis-stack#397]
I'm trying to find out if deploying the Redis Stack on Kubernetes is possible. The currently available options are provided by Btinami which supports simple replica and cluster setup. Any help/suggestions would be greatly appreciated.

**Comment by chayim** [comment]
Would a  [helm chart](https://github.com/redis-stack/helm-redis-stack) help?

**Comment by chayim** [comment]
@edbergavera Can we close this?

**Comment by edbergavera** [comment]
> @edbergavera Can we close this?

@chayim sorry, I have not tried the Helm chart as of yet, but yes we can close this issue. Thank you again for your support.

**Comment by edbergavera** [comment]
Hi @chayim , I tested the Helm chart and can confirm that it's working out of the box. Thank you. However, I need help setting up the password via config and persistent data using PVC. I highly appreciate your help.

**Comment by edbergavera** [comment]
@chayim Thank you for your response. I have tried the Bitnami Helm chart by updating some values like the docker image, and I was surprised to see that it works!

https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml

We can now close this issue. Thank you again for your support.

**Comment by pavankumar-go** [comment]
@chayim could you please update the [README.md](https://github.com/redis-stack/helm-redis-stack/blob/main/README.md) to include the `helm repo add ...` step please ? we cannot install `helm install redis-stack charts/redis-stack`  without adding the helm repo. thanks

**Comment by ofekshenawa** [comment]
Hello @pavankumar-go, we have updated the README.md file. You can now use the following command to add the repository: `helm repo add redis-stack https://redis-stack.github.io/helm-redis-stack/`.

**Comment by kamalkraj** [comment]
@ofekshenawa 

Is it possible to deploy `Redis-stack-server` using the master-slave setup?
1 Master and 2 or 3 Slave nodes.

**Comment by kamalkraj** [comment]
@edbergavera 
could you please share the helm chart you created for redis-stack ?

**Comment by edbergavera** [comment]
@kamalkraj this is the link https://github.com/redis-stack/redis-stack/issues/397#issuecomment-1590994514

**Comment by kamalkraj** [comment]
@edbergavera Is it possible to share the updated value.yaml file 

Thanks

**Comment by kamalkraj** [comment]
[Redis-Stack-Bitnami-Helm-Chart](https://github.com/kamalkraj/Redis-Stack-Bitnami-Helm-Chart)

Two files were modified to make it work

https://github.com/kamalkraj/Redis-Stack-Bitnami-Helm-Chart/blob/d74b379ca4db84cae037fa10a437d89b17284744/values.yaml#L93-L94

https://github.com/kamalkraj/Redis-Stack-Bitnami-Helm-Chart/blob/d74b379ca4db84cae037fa10a437d89b17284744/templates/scripts-configmap.yaml#L649-L652

https://github.com/kamalkraj/Redis-Stack-Bitnami-Helm-Chart/blob/d74b379ca4db84cae037fa10a437d89b17284744/templates/scripts-configmap.yaml#L759-L762

To run
```bash
git clone https://github.com/kamalkraj/Redis-Stack-Bitnami-Helm-Chart.git
cd Redis-Stack-Bitnami-Helm-Chart/
helm install redis-stack-server .
```

**Comment by chayim** [comment]
Between this choice, and [helm redis stack](https://github.com/redis-stack/helm-redis-stack) I think we can close :D
