### ISSUE TITLE
how to install windows server 2016

### ISSUE THREAD

**Issue by heaxo** [redis-stack/redis-stack#416]
The Docker OS/Arch installed on Windows 2016 server is Windows/amd64. Can Redis stack be installed on this version of Docker

**Comment by chayim** [comment]
Hi @heaxo I think you need these docs. https://redis.io/docs/getting-started/install-stack/windows/

Should you want to open an issue with regards to the documentation, you can do so here: https://github.com/redis-stack/redis-stack-docs
