### ISSUE TITLE
Upgraded instance no longer functions

### ISSUE THREAD

**Issue by zhiyan114** [redis-stack/redis-stack#458]
Related to https://stackoverflow.com/questions/76928167/how-to-migrate-redis-rdb-file-created-with-a-module-to-a-deployment-without-that

Essentially, after upgrade, the instance will no longer start up with the error `The RDB file contains AUX module data I can't load: no matching module 'graphdata'`.

There was a mention of `RedisGraphStub` being released as a dummy module, but I have yet to find it, so I'm just checking in on the status.

**Comment by jd-mateusz-prais** [comment]
Hi,

Why is this issue closed?

**Comment by zhiyan114** [comment]
I'm only using redis as a cache db, so deleting the dump file will work fine for me.

I can def reopen this if deleting the file isn't a viable solution for u.
