### ISSUE TITLE
Update etc/licenses/RSAL_LICENSE to V2

### ISSUE THREAD

**Issue by eredwine** [redis-stack/redis-stack#486]
https://github.com/redis-stack/redis-stack/pull/264 updated the License to be RSALv2 or SSPLv1. But, the license file etc/licenses/RSAL_LICENSE that is copied into the various images was left as V1. If this was just an oversight, could the etc/licenses/RSAL_LICENSE be updated to V2?

**Comment by chayim** [comment]
Thanks @eredwine they're definitely here in the repository, I'll ensure they make it into the various package releases.

**Comment by chayim** [comment]
@eredwine These are in all the branches, releases will happen in the next period. I'm going to close accordingly
