### ISSUE TITLE
Systemd service file missing after upgrading `redis-stack-server` package

### ISSUE THREAD

**Issue by guoard** [redis-stack/redis-stack#592]
I encountered an issue after upgrading the `redis-stack-server` package. The systemd service file located at `/etc/systemd/system/redis-stack-server.service` gets removed during the upgrade process.

Running `apt install --reinstall redis-stack-server` does not resolve the problem, as the systemd service file is not recreated.

However, purging the package with `apt purge redis-stack-server` and then reinstalling it with `apt install redis-stack-server` restores the systemd service file correctly.

1. What might be causing this issue? Why is the service file being removed during the upgrade?
2. Is the repository for the `.deb` package open-source? If so, where can I find it to further investigate?

**Comment by guoard** [comment]
> Maybe here https://github.com/redis-stack/redis-stack-deb ?

In that repository, the `.deb` file is downloaded from S3. Then, [this command](https://github.com/redis-stack/redis-stack-deb/blob/master/.github/workflows/RELEASE_REUSE.yml#L112) presets a passphrase, after which the file is uploaded back to S3. However, the actual content of the `.deb` file is not included.

**Comment by guoard** [comment]
It seems I’ve identified the line responsible for deleting the /etc/systemd/system/redis-stack-server.service file:

https://github.com/redis-stack/redis-stack/blob/master/etc/package/postremove#L4

**Comment by aminvakil** [comment]
Sometimes it does not execute `systemd daemon-reload` after installing or removing.

**Comment by guoard** [comment]
Closed in favor of #441
