### ISSUE TITLE
redis-stack does not install /etc/redis/redis.conf configuration file, but redis does

### ISSUE THREAD

**Issue by rkulagowski** [redis-stack/redis-stack#93]
Ubuntu 20.04

When installing redis using the instructions from
https://redis.io/docs/getting-started/installation/install-redis-on-linux/

the install process creates a 98 KiB file in /etc/redis/redis.conf

So, that's good.

However, installing redis-stack-server doesn't do anything similar, so redis launches with all defaults.

Therefore, when redis-stack-server is then launched as a user, you can't shutdown because the process can't write to /etc

$ redis-stack-server

(startup)

CTRL-C

```
^C28094:signal-handler (1650291975) Received SIGINT scheduling shutdown...
28094:M 18 Apr 2022 14:26:15.450 # User requested shutdown...
28094:M 18 Apr 2022 14:26:15.450 * Saving the final RDB snapshot before exiting.
28094:M 18 Apr 2022 14:26:15.451 # Failed opening the temp RDB file temp-28094.rdb (in server root dir /etc) for saving: Permission denied
28094:M 18 Apr 2022 14:26:15.451 # Error trying to save the DB, can't exit.
28094:M 18 Apr 2022 14:26:15.451 # Errors trying to shut down the server. Check the logs for more information.
```

Should there be a complete /etc/redis/redis.conf file when installing redis-stack-server which has "reasonable" defaults?
Should redis refuse to start if it can't write to the directory where it's going to store its RDB?

**Comment by chayim** [comment]
@rkulagowski This is by design. redis-stack-server will install a fail in /etc/redis-stack.conf on all unixes.  The systemd scripts use that script.

As redis-stack and redis can be installed side-by-side, we cannot change this behaviour.

@K-Jo Your call if you want to do something different here.

**Comment by chayim** [comment]
We're going to continue to maintain a separate configuration file for redis-stack as /etc/redis-stack.conf.
